distill::create_post(title= "articulo-01-09",	author = "Emerson Armando	Ramirez Gutierrez")
distill::create_post(title= "articulo-02-14",	author = "Joan Estibens	Trejos Marulanda")
distill::create_post(title= "articulo-03-11",	author = "Laura	Guerra Segura")
distill::create_post(title= "articulo-04-02",	author = "Marlon	Montero Guzman")
distill::create_post(title= "articulo-05-07",	author = "Santiago	Montaño Lopez")
distill::create_post(title= "articulo-06-03",	author = "Juan	Lozano Escobar")
distill::create_post(title= "articulo-07-16",	author = "Camila	Olarte Lopez")
distill::create_post(title= "articulo-08-04",	author = "Isabella	Gonzalez Mejia")
distill::create_post(title= "articulo-09-16",	author = "Gabriela	Quintero Moreno")
distill::create_post(title= "articulo-10-03",	author = "Gabriel	Rico Aragon")
distill::create_post(title= "articulo-11-06",	author = "Juan	Lopez Abella")
distill::create_post(title= "articulo-12-08", author = "Maria	Valencia Piedrahita")
distill::create_post(title= "articulo-13-10", author = "Alejandro	Cordoba Narvaez")
distill::create_post(title= "articulo-14-15", author = "Santiago	Valencia Amaya")
distill::create_post(title= "articulo-15-01", author = "David	Peña Molina")
distill::create_post(title= "articulo-16-02", author = "Juliana	Garzon Fajardo")
distill::create_post(title= "articulo-17-09", author = "Juan	Garcia Polanco")
distill::create_post(title= "articulo-18-12", author = "Dana	Torres Martinez")
distill::create_post(title= "articulo-19-04",	author = "Sebastian	Hurtado Bustos")
distill::create_post(title= "articulo-20-07",	author = "Alejandra	Herran Robledo")
distill::create_post(title= "articulo-21-06",	author = "Daniel	Izquierdo Cabrera")
distill::create_post(title= "articulo-22-15",	author = "Jose	Andrade Vargas")
distill::create_post(title= "articulo-23-13",	author = "Maria	Lozano Arcila")
distill::create_post(title= "articulo-24-01",	author = "Santiago	Ruiz Calero")
distill::create_post(title= "articulo-25-10",	author = "Saray	Garces Sanmartin")
distill::create_post(title= "articulo-26-01",	author = "Jean	Vasquez Pinilla")
distill::create_post(title= "articulo-27-05",	author = "Luis	Gaitan Zambrano")
distill::create_post(title= "articulo-28-08",	author = "Maria Camila	Betancourth Zapata")
distill::create_post(title= "articulo-29-03",	author = "Yeison	Muñoz Rodriguez")
distill::create_post(title= "articulo-30-11",	author = "Brenda	Torres Murcia")
distill::create_post(title= "articulo-31-12",	author = "Juan	Valencia Garcia")
distill::create_post(title= "articulo-32-05",	author = "Alvaro	Vargas Garcia")
distill::create_post(title= "articulo-33-07",	author = "Jesus	Valencia Sanchez")
distill::create_post(title= "articulo-34-14",	author = "Heber	Caicedo Garcia")
distill::create_post(title= "articulo-35-05",	author = "Juan	Marin Hincapie")
distill::create_post(title= "articulo-36-13",	author = "Isaac	Escobar")
distill::create_post(title= "articulo-37-08",	author = "Willian David	Chapid")

distill::create_theme(name = "theme", edit = TRUE)
